### ISSUE TITLE
problem with ETE

### ISSUE THREAD

**Issue by esud1** [UdeM-LBIT/CoreTracker#5]
Hi @maclandrol, 

Sorry to bother you again. 
I am having another problem with the CoreTracker. 
The program can run but it seems to stop at a certain point when predicting the possible codon reassignment. The run has never finished even after a few days. 
The only error message that I received was: 

`ETE: cannot connect to X server `

Do you know how to resolve this issue? 

Many thanks

**Comment by maclandrol** [comment]
Hello @esud1 , 

If you are having that error, it means the display server is missing.  Are you running coretracker on a server?  If yes, you would need to configure and enable **x-forwarding** (see https://kb.iu.edu/d/bdnt, for example).  Alternatively, you would need to install a virtual display like  **xvfb-run** (see https://helpmanual.io/help/xvfb-run/), then run all the coretracker command  like `xvfb-run coretracker [option]`. 

Regarding the time it is taking. Are you running the example dataset ? They should not take more than 10 min. What's the size of your dataset ? (how many species, genes) ? CoreTracker was designed with mitochondrial genome in mind first, so it can be a bit computationally intensive. However, something might be wrong if it is hanging indefinitely.

**Comment by esud1** [comment]
Hi @maclandrol, 

Thanks for your suggestion. 
I successfully run the program using xvfb-run.

A quick question, can we change the reference genetic code used in the analysis? 
I am using plastid genome data, but the reference genetic code used is 4 (mold mitochondrial). 
I looked around to change the genetic code in the parameter, but could not found any. 

Many thanks!

**Comment by maclandrol** [comment]
Glad to know that you got it to work. 

There is a set of extra parameters (in a yaml file) available with the option:  `---params param.yml` (see http://udem-lbit.github.io/CoreTracker/#usage)

An example of such a file is available at https://github.com/UdeM-LBIT/CoreTracker/blob/master/examples/test_data/param.yml

If you want to play around a bit, the complete list of variables that can be set in this file (yaml syntax) is defined at  https://github.com/UdeM-LBIT/CoreTracker/blob/master/coretracker/settings/parameters.py .

**Comment by esud1** [comment]
Great!

Many thanks for your input!
